### ISSUE TITLE
Error fuseMount command: geesefs

### ISSUE THREAD

**Issue by DTvGe45vc** [yandex-cloud/k8s-csi-s3#1]
Hello
I used default examples and got this log in managed k8s in Yandex Cloiud

MountVolume.SetUp failed for volume "pvc-9aa1554b-77f7-4cba-a9ee-e9cce6c9be3b" : rpc error: code = Unknown desc = Error fuseMount command: geesefs
args: [--endpoint https://storage.yandexcloud.net --region  -o allow_other --memory-limit 1000 --dir-mode 0777 --file-mode 0666 k8s-csi-s3:pvc-9aa1554b-77f7-4cba-a9ee-e9cce6c9be3b /var/lib/kubelet/pods/e4594844-fbd2-4c8c-874c-46b23bc3f6cb/volumes/kubernetes.io~csi/pvc-9aa1554b-77f7-4cba-a9ee-e9cce6c9be3b/mount]
output: 2021/09/06 11:06:59.226379 main.FATAL Unable to mount file system, see syslog for details

**Comment by vitalif** [comment]
Hi, I reproduced the problem, you can set region to any non-empty value (even "helloworld") as a quick workaround, it turns out that the driver doesn't currently work with empty region. I'll fix it shortly to work with empty region + I'll make it log to container stdout to make it possible to debug such situations by looking into `kubectl logs -n kube-system csi-s3-XXXXX csi-s3`.

**Comment by vitalif** [comment]
Done, try 0.26.2.
